name: Build and test spark image

on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
    paths:
      - Dockerfile
      - pom.xml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build image
        uses: docker/build-push-action@v1.1.0
        env:
          DOCKER_BUILDKIT: 1
        with:
          repository: basisai/workload-standard
          tag_with_ref: true
          push: false
